/**
 * Created by huweijian on 2017/4/4.
 * @title 定义常量
 */
export const JAVASCRIPT_DATA_TEST = 'JAVASCRIPT_DATA_TEST';

//全局常量
export const JAVASCRIPT_DATA_GLOBAL = 'JAVASCRIPT_DATA_GLOBAL';
export const JAVASCRIPT_DATA_GLOBAL_WARNING = 'JAVASCRIPT_DATA_GLOBAL_WARNING';
export const JAVASCRIPT_DATA_GLOBAL_LOADING = 'JAVASCRIPT_DATA_GLOBAL_LOADING';
export const JAVASCRIPT_DATA_GLOBAL_CODE = 'JAVASCRIPT_DATA_GLOBAL_CODE';

//数组常量
export const JAVASCRIPT_DATA_ARRAY_ACTIVITY_NAV = 'JAVASCRIPT_DATA_ARRAY_ACTIVITY_NAV';
export const JAVASCRIPT_DATA_ARRAY_CODE = 'JAVASCRIPT_DATA_ARRAY_CODE';
export const JAVASCRIPT_DATA_ARRAY_CODE_SET = 'JAVASCRIPT_DATA_ARRAY_CODE_SET';

//列表常量
export const JAVASCRIPT_DATA_LIST_ACTIVITY_NAV = 'JAVASCRIPT_DATA_LIST_ACTIVITY_NAV';
export const JAVASCRIPT_DATA_LIST_CODE_SET = 'JAVASCRIPT_DATA_LIST_CODE_SET';

//栈常量
export const JAVASCRIPT_DATA_STACK_ACTIVITY_NAV = 'JAVASCRIPT_DATA_STACK_ACTIVITY_NAV';
export const JAVASCRIPT_DATA_STACK_CODE_SET = 'JAVASCRIPT_DATA_STACK_CODE_SET';


//链表常量
export const JAVASCRIPT_DATA_LINK_INDEX = 'JAVASCRIPT_DATA_LINK_INDEX';
export const JAVASCRIPT_DATA_LINK_ACTIVITY_NAV = 'JAVASCRIPT_DATA_LINK_ACTIVITY_NAV';
export const JAVASCRIPT_DATA_LINK_ACTIVITY_NAV_CHILD = 'JAVASCRIPT_DATA_LINK_ACTIVITY_NAV_CHILD';
export const JAVASCRIPT_DATA_LINK_CODE = 'JAVASCRIPT_DATA_LINK_CODE';
export const JAVASCRIPT_DATA_LINK_CODE_SET = 'JAVASCRIPT_DATA_LINK_CODE_SET';






